### PR TITLE
Warbuilder fix and its itest

### PR DESCRIPTION
**Pull request by mkrizmanic**
Please merge the first commit. The second one is optional.

Thanks

### CODE REVIEW

**Comment by hwellmann** [comment]
Hi Mario - thanks for all your patches. If you start doing non-trivial stuff, please do write JIRA issues, so we can track changes in the release notes.

**Comment by mkrizmanic** [comment]
Hi, yes I'll and I have a question for you: how can I subscribe to receive email notifications for all JIRA issues or does the project have any mailing list?

Thanks

**Comment by ANierbeck** [comment]
yes, there are
ops4j@googlegroups.com and ops4j-notify@googlegroups.com

regards, Achim


2015-01-13 20:37 GMT+01:00 Mario Krizmanić <notifications@github.com>:

> Hi, yes I'll and I have a question for you: how can I subscribe to receive
> email notifications for all JIRA issues or does the project have any
> mailing list?
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ops4j/org.ops4j.pax.exam2/pull/29#issuecomment-69805208>
> .
>



-- 

Apache Member
Apache Karaf <http://karaf.apache.org/> Committer & PMC
OPS4J Pax Web <http://wiki.ops4j.org/display/paxweb/Pax+Web/> Committer &
Project Lead
blog <http://notizblog.nierbeck.de/>
Co-Author of Apache Karaf Cookbook <http://bit.ly/1ps9rkS>

Software Architect / Project Manager / Scrum Master

**Comment by mkrizmanic** [comment]
Thank you, Achim.

Harald, could you merge my patches?

**Comment by hwellmann** [comment]
Will do so, once you create a JIRA issue :-)

**Comment by mkrizmanic** [comment]
The JIRA issue are opened and the two commits are merged into one and renamed: https://ops4j1.jira.com/browse/PAXEXAM-676

Thanks

**Pull request merged**
