### PR TITLE
Add Karaf features as dependencies to test-dependency.xml

### PR DESCRIPTION
**Pull request by dario-cimafonte**

### CODE REVIEW

**Comment by hwellmann** [comment]
Hmm, I have no idea what you're trying to achieve...

In general, before submitting a pull request, please create a JIRA issue and state a problem or a feature request.

Next thing, please mind the coding and formatting conventions. There's an Eclipse formatter in `assets/EclipseJavaFormatter.xml`.

**Comment by dario-cimafonte** [comment]
Hi Harald,

Thank you for your feedback.

Sorry for the inconvenience, I couldn't find any mailing list where to ask.

I thought that if you add a karaf feature option, you want that feature to
be started before your probe does, and it makes sense to add it to the
generated features repository alongside other bundles.

I also took a chance to suggest a more conventional approach to unit
testing for that class.

If you think that this makes sense, I'm happy to open a Jira, and rework
the pull request.

Kind regards,
Dario
Il 27 nov 2015 20:05, "Harald Wellmann" <notifications@github.com> ha
scritto:

**Comment by ANierbeck** [comment]
You can find the jira issue here: 
https://ops4j1.jira.com/projects/PAXEXAM/summary
and a mailinglist is here: 
https://groups.google.com/forum/#!forum/ops4j

**Comment by dario-cimafonte** [comment]
I will rewrite this patch and then submit it following your advises, thank you.

**Pull request closed without merging**
